import os
import inspect
from pathlib import Path
from typing import Optional, Union
from fastapi import FastAPI, APIRouter, Request
from fastapi.dependencies.utils import solve_dependencies

from nexy.routers.actions.store import ACTIONS_STORE

class ActionEngine:
    def __init__(self, output_dir: Optional[str] = None):
        self.output_dir = output_dir
        # No logic in __init__ besides assignment to respect KISS
        
    def include_router(self, router: Union[FastAPI, APIRouter]):
        """
        Mounts all registered actions from ACTIONS_STORE onto the provided router.
        Uses hashed paths for security and unique identification.
        """
        print(ACTIONS_STORE.registry.items())
        for func_id, handler in ACTIONS_STORE.registry.items():
            path_hash = ACTIONS_STORE._generate_hash(func_id)
            encrypted_path = f"/_nx_{path_hash}"
            
            # Save the final path for the TS client generator
            ACTIONS_STORE.path_map[func_id] = encrypted_path
            print(f"Creating proxy for {func_id} at {encrypted_path}")

            def create_proxy(h=handler):
                async def proxy(request: Request):
                    # Handle POST JSON body
                    body = await request.json() if request.method == "POST" else {}
                    
                    # SOLID: Resolve dependencies via FastAPI's native utility
                    solved = await solve_dependencies(
                        request=request,
                        dependant=inspect.signature(h),
                        body=body
                    )
                    
                    final_kwargs = {**body, **solved.values}
                    
                    if inspect.iscoroutinefunction(h):
                        return await h(**final_kwargs)
                    return h(**final_kwargs)
                return proxy

            router.add_api_route(
                path=encrypted_path,
                endpoint=create_proxy(),
                methods=["POST"],
                name=f"Action: {func_id}"
            )
        return router

    def generate_client(self):
        """
        Generates TypeScript mirror files. 
        Only runs if output_dir is set and store is not empty.
        """
        if not self.output_dir or not ACTIONS_STORE.path_map:
            return

        out_path = Path(self.output_dir)
        
        for func_id, final_url in ACTIONS_STORE.path_map.items():
            # Mirror the Python module structure in the TS folders
            parts = func_id.split(".")
            func_name = parts.pop()
            
            sub_dir = out_path.joinpath(*parts)
            sub_dir.mkdir(parents=True, exist_ok=True)
            
            ts_code = [
                "/**",
                " * ⚡️ GENERATED BY NEXY - DO NOT EDIT MANUALLY",
                f" * Action ID: {func_id}",
                " */",
                "import { transport } from '@/nexy/client';",
                "",
                f"export const {func_name} = async (args: any): Promise<any> => {{",
                f"  return await transport.call('{final_url}', args);",
                "};"
            ]
            
            file_path = sub_dir / f"{func_name}.ts"
            with open(file_path, "w", encoding="utf-8") as f:
                f.write("\n".join(ts_code))

# Initialize with default path based on typical Nexy project structure
ACTION_ENGINE = ActionEngine(output_dir="./actions")