import importlib
import inspect
import pkgutil
import sys
from pathlib import Path
from typing import Any

from fastapi import FastAPI

from nexy.routers.actions.store import ACTIONS_STORE


class ActionEngine:
    def __init__(self, output_dir: str | None = None):
        self.output_dir = output_dir
        self.ignore_folders = {
            "__pycache__",
            ".venv",
            "venv",
            "node_modules",
            ".git",
            "dist",
            "build",
        }

    def discover(self, start_dir: str = "src"):
        """
        Dynamically imports modules while skipping ignored directories.
        """
        base_path = Path(start_dir).resolve()
        if not base_path.exists():
            return

        if str(base_path.parent) not in sys.path:
            sys.path.append(str(base_path.parent))

        # walk_packages starts scanning
        for loader, name, is_pkg in pkgutil.walk_packages([str(base_path)]):
            # Optimization: check if any part of the module path is in ignore_folders
            # Example: 'src.node_modules.test' -> ['src', 'node_modules', 'test']
            parts = name.split(".")
            if any(ignored in parts for ignored in self.ignore_folders):
                continue

            try:
                importlib.import_module(name)
            except Exception:
                # We skip modules with import errors to keep the engine running
                continue

    def include_router(self, router: FastAPI):
        """
        Mounts all registered actions onto the router.
        """
        # We check the registry here
        for func_id, handler in ACTIONS_STORE.registry.items():
            path_hash = ACTIONS_STORE._generate_hash(func_id)
            encrypted_path = f"/_nx_{path_hash}"

            ACTIONS_STORE.path_map[func_id] = encrypted_path

            router.add_api_route(
                path=encrypted_path,
                endpoint=handler,
                methods=["POST"],
                name=handler.__name__,
                tags=["All Actions"],
            )
        return router

    def _map_py_type_to_ts(self, py_type: Any) -> str:
        """KISS: Simple mapping from Python types to TypeScript types."""
        if py_type is int or py_type is float:
            return "number"
        if py_type is str:
            return "string"
        if py_type is bool:
            return "boolean"

        # Handle typing generics (List, Dict, etc.)
        origin = getattr(py_type, "__origin__", None)
        if origin is list or py_type is list:
            return "any[]"
        if origin is dict or py_type is dict:
            return "{ [key: string]: any }"

        return "any"

    def generate_client(self):
        """Generates TypeScript mirror files with basic type safety."""
        if not self.output_dir or not ACTIONS_STORE.path_map:
            return

        out_path = Path(self.output_dir)
        for func_id, final_url in ACTIONS_STORE.path_map.items():
            handler = ACTIONS_STORE.registry.get(func_id)
            if not handler:
                continue

            parts = func_id.split(".")
            func_name = parts.pop()

            sub_dir = out_path.joinpath(*parts)
            sub_dir.mkdir(parents=True, exist_ok=True)

            # Extract signature for type safety
            sig = inspect.signature(handler)
            params = []
            for name, param in sig.parameters.items():
                if name in ("request", "response"):  # Skip FastAPI internals
                    continue
                ts_type = self._map_py_type_to_ts(param.annotation)
                params.append(f"{name}: {ts_type}")

            arg_line = ", ".join(params)
            ret_type = self._map_py_type_to_ts(sig.return_annotation)

            ts_code = [
                "/**",
                " * GENERATED BY NEXY",
                f" * Action ID: {func_id}",
                " */",
                "import { transport } from '@/nexy/client';",
                "",
                f"export const {func_name} = async ({arg_line}): Promise<{ret_type}> => {{",
                f"  return await transport.call('{final_url}', {{ {', '.join(p.split(':')[0] for p in params)} }});",
                "};",
            ]

            file_path = sub_dir / f"{func_name}.ts"
            file_path.write_text("\n".join(ts_code), encoding="utf-8")


ACTION_ENGINE = ActionEngine(output_dir="./actions")
ACTION_ENGINE.discover("src")
