import os
import inspect
import pkgutil
import importlib
from pathlib import Path
import sys
from typing import Optional, Union, Any
from fastapi import FastAPI, Request
from fastapi.dependencies.utils import solve_dependencies

from nexy.routers.actions.store import ACTIONS_STORE

class ActionEngine:
    def __init__(self, output_dir: Optional[str] = None):
        self.output_dir = output_dir
        self.ignore_folders = {
            "__pycache__", 
            ".venv", 
            "venv", 
            "node_modules", 
            ".git", 
            "dist", 
            "build"
        }

    def discover(self, start_dir: str = "src"):
        """
        Dynamically imports modules while skipping ignored directories.
        """
        base_path = Path(start_dir).resolve()
        if not base_path.exists():
            return

        if str(base_path.parent) not in sys.path:
            sys.path.append(str(base_path.parent))
        
        # walk_packages starts scanning
        for loader, name, is_pkg in pkgutil.walk_packages([str(base_path)]):
            # Optimization: check if any part of the module path is in ignore_folders
            # Example: 'src.node_modules.test' -> ['src', 'node_modules', 'test']
            parts = name.split(".")
            if any(ignored in parts for ignored in self.ignore_folders):
                continue
                
            try:
                importlib.import_module(name)
            except Exception:
                # We skip modules with import errors to keep the engine running
                continue

    def include_router(self, router: FastAPI):
        """
        Mounts all registered actions onto the router.
        """
        # We check the registry here
        for func_id, handler in ACTIONS_STORE.registry.items():
            path_hash = ACTIONS_STORE._generate_hash(func_id)
            encrypted_path = f"/_nx_{path_hash}"
            
            ACTIONS_STORE.path_map[func_id] = encrypted_path
            
            router.add_api_route(
                path=encrypted_path,
                endpoint=handler,
                methods=["POST"],
                name=handler.__name__, 
                tags=["All Actions"]
            )
        return router

    def generate_client(self):
        """Generates TypeScript mirror files."""
        if not self.output_dir or not ACTIONS_STORE.path_map:
            return

        out_path = Path(self.output_dir)
        for func_id, final_url in ACTIONS_STORE.path_map.items():
            parts = func_id.split(".")
            func_name = parts.pop()
            
            sub_dir = out_path.joinpath(*parts)
            sub_dir.mkdir(parents=True, exist_ok=True)
            
            ts_code = [
                "/**",
                " * GENERATED BY NEXY",
                f" * Action ID: {func_id}",
                " */",
                "import { transport } from '@/nexy/client';",
                "",
                f"export const {func_name} = async (args: any): Promise<any> => {{",
                f"  return await transport.call('{final_url}', args);",
                "};"
            ]
            
            file_path = sub_dir / f"{func_name}.ts"
            file_path.write_text("\n".join(ts_code), encoding="utf-8")


ACTION_ENGINE = ActionEngine(output_dir="./actions")
ACTION_ENGINE.discover("./")

