from typing import Any

_SAFE_BUILTINS: dict[str, Any] = {
    "True": True,
    "False": False,
    "None": None,
    "bool": bool,
    "int": int,
    "float": float,
    "str": str,
    "bytes": bytes,
    "list": list,
    "dict": dict,
    "tuple": tuple,
    "set": set,
    "frozenset": frozenset,
    "complex": complex,
    "abs": abs,
    "min": min,
    "max": max,
    "sum": sum,
    "pow": pow,
    "round": round,
    "divmod": divmod,
    "len": len,
    "range": range,
    "enumerate": enumerate,
    "zip": zip,
    "map": map,
    "filter": filter,
    "reversed": reversed,
    "sorted": sorted,
    "slice": slice,
    "iter": iter,
    "next": next,
    "any": any,
    "all": all,
    "isinstance": isinstance,
    "issubclass": issubclass,
    "hasattr": hasattr,
    "getattr": getattr,
    "setattr": setattr,
    "delattr": delattr,
    "type": type,
    "callable": callable,
    "id": id,
    "hash": hash,
    "repr": repr,
    "ascii": ascii,
    "chr": chr,
    "ord": ord,
    "hex": hex,
    "oct": oct,
    "bin": bin,
    "format": format,
    "print": print,
    "staticmethod": staticmethod,
    "classmethod": classmethod,
    "property": property,
    "super": super,
    "object": object,
    "Exception": Exception,
    "ValueError": ValueError,
    "TypeError": TypeError,
    "KeyError": KeyError,
    "AttributeError": AttributeError,
    "IndexError": IndexError,
    "StopIteration": StopIteration,
    "RuntimeError": RuntimeError,
    "ImportError": ImportError,
    "NameError": NameError,
    "LookupError": LookupError,
    "ArithmeticError": ArithmeticError,
    "ZeroDivisionError": ZeroDivisionError,
}

_DENIED_NAMES = frozenset(
    {
        "__import__",
        "open",
        "exec",
        "eval",
        "compile",
        "globals",
        "locals",
        "vars",
        "dir",
        "memoryview",
        "breakpoint",
        "input",
        "exit",
        "quit",
        "help",
        "__builtins__",
    }
)


def sandboxed_exec(code: str, namespace: dict[str, Any]) -> None:
    for name in _DENIED_NAMES:
        if name in namespace:
            raise NameError(f"'{name}' is not allowed in component logic")
    exec(code, {"__builtins__": _SAFE_BUILTINS}, namespace)
